# Generated by Django 5.2.6 on 2025-10-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_apikey_plain_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='trial_quota',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='used_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='plan',
            field=models.CharField(choices=[('trial', 'trial'), ('pro', 'pro'), ('demo', 'demo')], default='demo', max_length=16),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('revoked', 'revoked')], default='active', max_length=16),
        ),
    ]
